//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSN_Payer.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSN_Payer.Resources.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billssign.
        /// </summary>
        internal static string BillsSignImage {
            get {
                return ResourceManager.GetString("BillsSignImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #02946F.
        /// </summary>
        internal static string BtnBackgroundColor {
            get {
                return ResourceManager.GetString("BtnBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #cc8400.
        /// </summary>
        internal static string BtnCancelBackground {
            get {
                return ResourceManager.GetString("BtnCancelBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Card number does not match the card type (i.e., VISA, Discover) you selected. Please choose the appropriate card type or re-enter the card number..
        /// </summary>
        internal static string CardNoNotMatched {
            get {
                return ResourceManager.GetString("CardNoNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks are accepted under these conditions. When you pay by check and if your check is dishonored or returned for any reason, you expressly authorize this merchant to electronically debit your account for the amount of the check plus an NSF fee and any other recovery fees allowed by the State of your checking account and any applicable sales tax that may apply. The use of a check for payment and agreement to these terms is herein agreed by selecting OK and click [Process Payment] to complete your payment pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckConfirmMsg {
            get {
                return ResourceManager.GetString("CheckConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        internal static string CheckedStatus {
            get {
                return ResourceManager.GetString("CheckedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation email has been sent to your email..
        /// </summary>
        internal static string ConfirmationOnEmail {
            get {
                return ResourceManager.GetString("ConfirmationOnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payment Info.
        /// </summary>
        internal static string ConfirmPaymentHeadMsg {
            get {
                return ResourceManager.GetString("ConfirmPaymentHeadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string ConfirmToDelete {
            get {
                return ResourceManager.GetString("ConfirmToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfPayBlank.
        /// </summary>
        internal static string ConfPayBlank {
            get {
                return ResourceManager.GetString("ConfPayBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfPayFilled.
        /// </summary>
        internal static string ConfPayFilled {
            get {
                return ResourceManager.GetString("ConfPayFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi network is not connected or low bandwidth.
        /// </summary>
        internal static string CrossConnectivityError {
            get {
                return ResourceManager.GetString("CrossConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        internal static string DashboardIcon {
            get {
                return ResourceManager.GetString("DashboardIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psnlogolg.
        /// </summary>
        internal static string DashboardLogo {
            get {
                return ResourceManager.GetString("DashboardLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exp Date must not be in the past.
        /// </summary>
        internal static string DateNotbeinPast {
            get {
                return ResourceManager.GetString("DateNotbeinPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string DownloadImage {
            get {
                return ResourceManager.GetString("DownloadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled out.
        /// </summary>
        internal static string FilledMandatory {
            get {
                return ResourceManager.GetString("FilledMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #57CBB2.
        /// </summary>
        internal static string HamburgerBarColor {
            get {
                return ResourceManager.GetString("HamburgerBarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psnlogonav.png.
        /// </summary>
        internal static string HeaderNavLogo {
            get {
                return ResourceManager.GetString("HeaderNavLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment history for past 30 days.
        /// </summary>
        internal static string HistoryHeadMessage {
            get {
                return ResourceManager.GetString("HistoryHeadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        internal static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savings.
        /// </summary>
        internal static string IsSavings {
            get {
                return ResourceManager.GetString("IsSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string LblAcctNo {
            get {
                return ResourceManager.GetString("LblAcctNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string LblCardNo {
            get {
                return ResourceManager.GetString("LblCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Date.
        /// </summary>
        internal static string LblExpDate {
            get {
                return ResourceManager.GetString("LblExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method Type.
        /// </summary>
        internal static string LblMethodType {
            get {
                return ResourceManager.GetString("LblMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        internal static string LblNameOnCard {
            get {
                return ResourceManager.GetString("LblNameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick Name.
        /// </summary>
        internal static string LblNickName {
            get {
                return ResourceManager.GetString("LblNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Number.
        /// </summary>
        internal static string LblRoutingNo {
            get {
                return ResourceManager.GetString("LblRoutingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string LblZipCode {
            get {
                return ResourceManager.GetString("LblZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D1F2EB.
        /// </summary>
        internal static string LoaderBackGround {
            get {
                return ResourceManager.GetString("LoaderBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate email address.
        /// </summary>
        internal static string LoginError101 {
            get {
                return ResourceManager.GetString("LoginError101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate contact number.
        /// </summary>
        internal static string LoginError102 {
            get {
                return ResourceManager.GetString("LoginError102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string LoginError150 {
            get {
                return ResourceManager.GetString("LoginError150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has no password/not setup.
        /// </summary>
        internal static string LoginError195 {
            get {
                return ResourceManager.GetString("LoginError195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown login error.
        /// </summary>
        internal static string LoginError199 {
            get {
                return ResourceManager.GetString("LoginError199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen2.
        /// </summary>
        internal static string LoginScreenBackgroundPortrait {
            get {
                return ResourceManager.GetString("LoginScreenBackgroundPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct email or password.
        /// </summary>
        internal static string LoginScreenInCorrectCredentials {
            get {
                return ResourceManager.GetString("LoginScreenInCorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payment amount.
        /// </summary>
        internal static string MakePaymentReq1 {
            get {
                return ResourceManager.GetString("MakePaymentReq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payment date.
        /// </summary>
        internal static string MakePaymentReq2 {
            get {
                return ResourceManager.GetString("MakePaymentReq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value between.
        /// </summary>
        internal static string MakePaymentVal1Msg {
            get {
                return ResourceManager.GetString("MakePaymentVal1Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bills.
        /// </summary>
        internal static string MenuItemIconBills {
            get {
                return ResourceManager.GetString("MenuItemIconBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string MenuItemIconHistory {
            get {
                return ResourceManager.GetString("MenuItemIconHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string MenuItemIconLogout {
            get {
                return ResourceManager.GetString("MenuItemIconLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to makepayment.
        /// </summary>
        internal static string MenuItemIconMakePayment {
            get {
                return ResourceManager.GetString("MenuItemIconMakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paymentmethod.
        /// </summary>
        internal static string MenuItemIconPaymentMethod {
            get {
                return ResourceManager.GetString("MenuItemIconPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string MenuItemIconSettings {
            get {
                return ResourceManager.GetString("MenuItemIconSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string MenuItemImageArrow {
            get {
                return ResourceManager.GetString("MenuItemImageArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        internal static string NoBillGenerated {
            get {
                return ResourceManager.GetString("NoBillGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayInfoBlank.
        /// </summary>
        internal static string PayInfoBlank {
            get {
                return ResourceManager.GetString("PayInfoBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayInfoFilled.
        /// </summary>
        internal static string PayInfoFilled {
            get {
                return ResourceManager.GetString("PayInfoFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Payment Info.
        /// </summary>
        internal static string PaymentInfoHeadMsg {
            get {
                return ResourceManager.GetString("PaymentInfoHeadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter account number.
        /// </summary>
        internal static string PaymentMethodAcctNo {
            get {
                return ResourceManager.GetString("PaymentMethodAcctNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Banking Added Successfully.
        /// </summary>
        internal static string PaymentMethodAdded {
            get {
                return ResourceManager.GetString("PaymentMethodAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter card number.
        /// </summary>
        internal static string PaymentMethodCardNo {
            get {
                return ResourceManager.GetString("PaymentMethodCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error:paymentmethodhasincorrecttypedefinition..
        /// </summary>
        internal static string PaymentMethodIncorrectDefinition {
            get {
                return ResourceManager.GetString("PaymentMethodIncorrectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter month.
        /// </summary>
        internal static string PaymentMethodMonth {
            get {
                return ResourceManager.GetString("PaymentMethodMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter month between 1 to 12.
        /// </summary>
        internal static string PaymentMethodMonth1T12 {
            get {
                return ResourceManager.GetString("PaymentMethodMonth1T12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter nick name.
        /// </summary>
        internal static string PaymentMethodNickName {
            get {
                return ResourceManager.GetString("PaymentMethodNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter routing number.
        /// </summary>
        internal static string PaymentMethodRoutingNo {
            get {
                return ResourceManager.GetString("PaymentMethodRoutingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid card number.
        /// </summary>
        internal static string PaymentMethodValCardNo {
            get {
                return ResourceManager.GetString("PaymentMethodValCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid date.
        /// </summary>
        internal static string PaymentMethodValDate {
            get {
                return ResourceManager.GetString("PaymentMethodValDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select method type.
        /// </summary>
        internal static string PaymentMethodValMethodType {
            get {
                return ResourceManager.GetString("PaymentMethodValMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name on.
        /// </summary>
        internal static string PaymentMethodValNameOn {
            get {
                return ResourceManager.GetString("PaymentMethodValNameOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid year.
        /// </summary>
        internal static string PaymentMethodValYear {
            get {
                return ResourceManager.GetString("PaymentMethodValYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter year.
        /// </summary>
        internal static string PaymentMethodYear {
            get {
                return ResourceManager.GetString("PaymentMethodYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        internal static string PaymentMethodZip {
            get {
                return ResourceManager.GetString("PaymentMethodZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayReceiptBlank.
        /// </summary>
        internal static string PayReceiptBlank {
            get {
                return ResourceManager.GetString("PayReceiptBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayReceiptFilled.
        /// </summary>
        internal static string PayReceiptFilled {
            get {
                return ResourceManager.GetString("PayReceiptFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        internal static string PendingStatus {
            get {
                return ResourceManager.GetString("PendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #999999.
        /// </summary>
        internal static string PickerOutlineColor {
            get {
                return ResourceManager.GetString("PickerOutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;^([0-9])*$&quot;.
        /// </summary>
        internal static string RegexNumber {
            get {
                return ResourceManager.GetString("RegexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string RejectedStatus {
            get {
                return ResourceManager.GetString("RejectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Password.
        /// </summary>
        internal static string ReqMsgLoginPassword {
            get {
                return ResourceManager.GetString("ReqMsgLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter UserID.
        /// </summary>
        internal static string ReqMsgLoginUserID {
            get {
                return ResourceManager.GetString("ReqMsgLoginUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8Rd28e+QHUkakFu+PrjasQ==.
        /// </summary>
        internal static string SecurityKey {
            get {
                return ResourceManager.GetString("SecurityKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://beta.paymentservicenetwork.com/PSNSoftNet/PTPMobile.asmx?op=.
        /// </summary>
        internal static string ServicePathBeta {
            get {
                return ResourceManager.GetString("ServicePathBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paymentservicenetwork.com/PSNSoftNet/PTPMobile.asmx?op=.
        /// </summary>
        internal static string ServicePathProduction {
            get {
                return ResourceManager.GetString("ServicePathProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password..
        /// </summary>
        internal static string SettingConfirmPassError {
            get {
                return ResourceManager.GetString("SettingConfirmPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct old password..
        /// </summary>
        internal static string SettingCorrectOldPassError {
            get {
                return ResourceManager.GetString("SettingCorrectOldPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password..
        /// </summary>
        internal static string SettingNewPassError {
            get {
                return ResourceManager.GetString("SettingNewPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter old password..
        /// </summary>
        internal static string SettingOldPassError {
            get {
                return ResourceManager.GetString("SettingOldPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed sucessfully..
        /// </summary>
        internal static string SettingPassChanged {
            get {
                return ResourceManager.GetString("SettingPassChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password do not match with New password..
        /// </summary>
        internal static string SettingPassDontMatch {
            get {
                return ResourceManager.GetString("SettingPassDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be less than 6 characters..
        /// </summary>
        internal static string SettingPassWarning {
            get {
                return ResourceManager.GetString("SettingPassWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paymentservicenetwork.com/mobile/search.aspx.
        /// </summary>
        internal static string SignUpURL {
            get {
                return ResourceManager.GetString("SignUpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred !!.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
